language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# Temporarily use xenial with with sudo to install Python 3.7 and dev releases
# References:
# https://github.com/travis-ci/travis-ci/issues/9069
# https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - language: generic
      os: osx
    - python: "3.6-dev"
      dist: xenial
      sudo: required
    - python: "3.7"
      dist: xenial
      sudo: required
    - python: "3.7-dev"
      dist: xenial
      sudo: required
    - python: "3.8-dev"
      dist: xenial
      sudo: required
    - python: "nightly"
      dist: xenial
      sudo: required
  allow_failures:
    - python: "3.8-dev"
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"

# Install Python on OSX
install:
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update ; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew upgrade python; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then pip3 install virtualenv; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then virtualenv venv -p python3; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then source venv/bin/activate; fi

# Command to run tests
script: py.test
